baseURL = "https://nwyn-07.github.io/"
languageCode = "vi-VN"
title = "Blog Lập Trình Mạng"
theme = "PaperMod"

[params]
  description = "Blog chia sẻ kiến thức Java & JavaScript"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "AboutMe"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3